version: '3.4'
services:
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/sites-available
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=menherachan.cf
      - NGINX_PORT=80
    networks:
      - frontend

  mariadb:
    image: mariadb:10.2
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadbtest
      MYSQL_DATABASE: Menherachan
      MYSQL_USER: menherachan
      MYSQL_PASSWORD: menherachan__jopa12
    networks:
      - backend
        
  menherachan:
    build: .
    environment:
      - 'MariaDbConnection=server=mariadb;port=3306;database=Menherachan;uid=menherachan;pwd=menherachan__jopa12;treattinyasboolean=false'
    networks:
      - frontend
      - backend
    
  volumes:
    templates:
    mariadb:
      
  networks:
    frontend:
    backend:
    